# version: '3.9'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: abcdEF@12
      POSTGRES_DB: synthhms
    volumes:
      - medivyx_pgdata:/var/lib/postgresql/data
      - ./postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf
    command: postgres -c config_file=/usr/local/etc/postgres/postgres.conf
    ports:
      - '5432:5432'

  redis:
    image: redis:7
    restart: always
    command: redis-server --requirepass medplum
    ports:
      - '6379:6379'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medivyx-backend
    ports:
      - '8103:8103'
    volumes:
      - ./medplum.config.docker.json:/usr/src/medivyx/packages/server/medplum.config.json
      - medivyx_binary:/usr/src/medivyx/binary
    environment:
      MEDPLUM_PORT: 8103
      # MEDPLUM_BASE_URL: 'http://localhost:8103'
      # MEDPLUM_APP_BASE_URL: 'http://localhost:3000'
      # MEDPLUM_STORAGE_BASE_URL: 'http://localhost:8103/storage'
      MEDPLUM_DATABASE_HOST: postgres
      MEDPLUM_DATABASE_PORT: 5432
      MEDPLUM_DATABASE_DBNAME: synthhms
      MEDPLUM_DATABASE_USERNAME: admin
      MEDPLUM_DATABASE_PASSWORD: abcdEF@12
      MEDPLUM_REDIS_HOST: redis
      MEDPLUM_REDIS_PORT: 6379
      MEDPLUM_REDIS_PASSWORD: medplum
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: .
      dockerfile: packages/app/Dockerfile
    container_name: medivyx-frontend
    ports:
      - "3000:8080"
    depends_on:
      - backend

volumes:
  medivyx_pgdata:
  medivyx_binary:
